name: Siyadong Xiong
url: http://sidxiong.github.io
markdown: kramdown
kramdown:
    parse_block_html: true

highlighter: rouge

permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

analytics :
    provider : google 
    google : 
        tracking_id : 'UA-88884216-1'

description: Sid Xiong personal page
weibo: xsyd


