name: Siyadong Xiong
url: http://siyadong.me

markdown: kramdown

kramdown:
    parse_block_html: true

highlighter: rouge

permalink: /content/:year/:title

rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

analytics :
    provider : google 
    google : 
        tracking_id : 'UA-88884216-1'

description: Sid Xiong personal page
weibo: xsyd

excerpt_separator: <!--more-->
